// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Gamium.Protocol.Packets
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ActionsParam : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_10_26(); }
  public static ActionsParam GetRootAsActionsParam(ByteBuffer _bb) { return GetRootAsActionsParam(_bb, new ActionsParam()); }
  public static ActionsParam GetRootAsActionsParam(ByteBuffer _bb, ActionsParam obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ActionsParam __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public sbyte Actions(int j) { int o = __p.__offset(4); return o != 0 ? __p.bb.GetSbyte(__p.__vector(o) + j * 1) : (sbyte)0; }
  public int ActionsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<sbyte> GetActionsBytes() { return __p.__vector_as_span<sbyte>(4, 1); }
#else
  public ArraySegment<byte>? GetActionsBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public sbyte[] GetActionsArray() { return __p.__vector_as_array<sbyte>(4); }

  public static Offset<Gamium.Protocol.Packets.ActionsParam> CreateActionsParam(FlatBufferBuilder builder,
      VectorOffset actionsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    ActionsParam.AddActions(builder, actionsOffset);
    return ActionsParam.EndActionsParam(builder);
  }

  public static void StartActionsParam(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddActions(FlatBufferBuilder builder, VectorOffset actionsOffset) { builder.AddOffset(0, actionsOffset.Value, 0); }
  public static VectorOffset CreateActionsVector(FlatBufferBuilder builder, sbyte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddSbyte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateActionsVectorBlock(FlatBufferBuilder builder, sbyte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateActionsVectorBlock(FlatBufferBuilder builder, ArraySegment<sbyte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateActionsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<sbyte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartActionsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static Offset<Gamium.Protocol.Packets.ActionsParam> EndActionsParam(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Gamium.Protocol.Packets.ActionsParam>(o);
  }
  public ActionsParamT UnPack() {
    var _o = new ActionsParamT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ActionsParamT _o) {
    _o.Actions = new List<sbyte>();
    for (var _j = 0; _j < this.ActionsLength; ++_j) {_o.Actions.Add(this.Actions(_j));}
  }
  public static Offset<Gamium.Protocol.Packets.ActionsParam> Pack(FlatBufferBuilder builder, ActionsParamT _o) {
    if (_o == null) return default(Offset<Gamium.Protocol.Packets.ActionsParam>);
    var _actions = default(VectorOffset);
    if (_o.Actions != null) {
      var __actions = _o.Actions.ToArray();
      _actions = CreateActionsVector(builder, __actions);
    }
    return CreateActionsParam(
      builder,
      _actions);
  }
}

public class ActionsParamT
{
  public List<sbyte> Actions { get; set; }

  public ActionsParamT() {
    this.Actions = null;
  }
}


}
