// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Gamium.Protocol.Packets
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct InspectObjectOnScreenResult : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_10_26(); }
  public static InspectObjectOnScreenResult GetRootAsInspectObjectOnScreenResult(ByteBuffer _bb) { return GetRootAsInspectObjectOnScreenResult(_bb, new InspectObjectOnScreenResult()); }
  public static InspectObjectOnScreenResult GetRootAsInspectObjectOnScreenResult(ByteBuffer _bb, InspectObjectOnScreenResult obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public InspectObjectOnScreenResult __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Gamium.Protocol.Types.ObjectInfo? Infos(int j) { int o = __p.__offset(4); return o != 0 ? (Gamium.Protocol.Types.ObjectInfo?)(new Gamium.Protocol.Types.ObjectInfo()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int InfosLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public Gamium.Protocol.Types.Vector3? HitPoint { get { int o = __p.__offset(6); return o != 0 ? (Gamium.Protocol.Types.Vector3?)(new Gamium.Protocol.Types.Vector3()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static Offset<Gamium.Protocol.Packets.InspectObjectOnScreenResult> CreateInspectObjectOnScreenResult(FlatBufferBuilder builder,
      VectorOffset infosOffset = default(VectorOffset),
      Gamium.Protocol.Types.Vector3T hit_point = null) {
    builder.StartTable(2);
    InspectObjectOnScreenResult.AddHitPoint(builder, Gamium.Protocol.Types.Vector3.Pack(builder, hit_point));
    InspectObjectOnScreenResult.AddInfos(builder, infosOffset);
    return InspectObjectOnScreenResult.EndInspectObjectOnScreenResult(builder);
  }

  public static void StartInspectObjectOnScreenResult(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddInfos(FlatBufferBuilder builder, VectorOffset infosOffset) { builder.AddOffset(0, infosOffset.Value, 0); }
  public static VectorOffset CreateInfosVector(FlatBufferBuilder builder, Offset<Gamium.Protocol.Types.ObjectInfo>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateInfosVectorBlock(FlatBufferBuilder builder, Offset<Gamium.Protocol.Types.ObjectInfo>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateInfosVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Gamium.Protocol.Types.ObjectInfo>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateInfosVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Gamium.Protocol.Types.ObjectInfo>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartInfosVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddHitPoint(FlatBufferBuilder builder, Offset<Gamium.Protocol.Types.Vector3> hitPointOffset) { builder.AddStruct(1, hitPointOffset.Value, 0); }
  public static Offset<Gamium.Protocol.Packets.InspectObjectOnScreenResult> EndInspectObjectOnScreenResult(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Gamium.Protocol.Packets.InspectObjectOnScreenResult>(o);
  }
  public InspectObjectOnScreenResultT UnPack() {
    var _o = new InspectObjectOnScreenResultT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(InspectObjectOnScreenResultT _o) {
    _o.Infos = new List<Gamium.Protocol.Types.ObjectInfoT>();
    for (var _j = 0; _j < this.InfosLength; ++_j) {_o.Infos.Add(this.Infos(_j).HasValue ? this.Infos(_j).Value.UnPack() : null);}
    _o.HitPoint = this.HitPoint.HasValue ? this.HitPoint.Value.UnPack() : null;
  }
  public static Offset<Gamium.Protocol.Packets.InspectObjectOnScreenResult> Pack(FlatBufferBuilder builder, InspectObjectOnScreenResultT _o) {
    if (_o == null) return default(Offset<Gamium.Protocol.Packets.InspectObjectOnScreenResult>);
    var _infos = default(VectorOffset);
    if (_o.Infos != null) {
      var __infos = new Offset<Gamium.Protocol.Types.ObjectInfo>[_o.Infos.Count];
      for (var _j = 0; _j < __infos.Length; ++_j) { __infos[_j] = Gamium.Protocol.Types.ObjectInfo.Pack(builder, _o.Infos[_j]); }
      _infos = CreateInfosVector(builder, __infos);
    }
    return CreateInspectObjectOnScreenResult(
      builder,
      _infos,
      _o.HitPoint);
  }
}

public class InspectObjectOnScreenResultT
{
  public List<Gamium.Protocol.Types.ObjectInfoT> Infos { get; set; }
  public Gamium.Protocol.Types.Vector3T HitPoint { get; set; }

  public InspectObjectOnScreenResultT() {
    this.Infos = null;
    this.HitPoint = new Gamium.Protocol.Types.Vector3T();
  }
}


}
