// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Gamium.Protocol.Packets
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct InspectObjectWithIdParam : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_10_26(); }
  public static InspectObjectWithIdParam GetRootAsInspectObjectWithIdParam(ByteBuffer _bb) { return GetRootAsInspectObjectWithIdParam(_bb, new InspectObjectWithIdParam()); }
  public static InspectObjectWithIdParam GetRootAsInspectObjectWithIdParam(ByteBuffer _bb, InspectObjectWithIdParam obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public InspectObjectWithIdParam __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string ObjectId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetObjectIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetObjectIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetObjectIdArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<Gamium.Protocol.Packets.InspectObjectWithIdParam> CreateInspectObjectWithIdParam(FlatBufferBuilder builder,
      StringOffset object_idOffset = default(StringOffset)) {
    builder.StartTable(1);
    InspectObjectWithIdParam.AddObjectId(builder, object_idOffset);
    return InspectObjectWithIdParam.EndInspectObjectWithIdParam(builder);
  }

  public static void StartInspectObjectWithIdParam(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddObjectId(FlatBufferBuilder builder, StringOffset objectIdOffset) { builder.AddOffset(0, objectIdOffset.Value, 0); }
  public static Offset<Gamium.Protocol.Packets.InspectObjectWithIdParam> EndInspectObjectWithIdParam(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Gamium.Protocol.Packets.InspectObjectWithIdParam>(o);
  }
  public InspectObjectWithIdParamT UnPack() {
    var _o = new InspectObjectWithIdParamT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(InspectObjectWithIdParamT _o) {
    _o.ObjectId = this.ObjectId;
  }
  public static Offset<Gamium.Protocol.Packets.InspectObjectWithIdParam> Pack(FlatBufferBuilder builder, InspectObjectWithIdParamT _o) {
    if (_o == null) return default(Offset<Gamium.Protocol.Packets.InspectObjectWithIdParam>);
    var _object_id = _o.ObjectId == null ? default(StringOffset) : builder.CreateString(_o.ObjectId);
    return CreateInspectObjectWithIdParam(
      builder,
      _object_id);
  }
}

public class InspectObjectWithIdParamT
{
  public string ObjectId { get; set; }

  public InspectObjectWithIdParamT() {
    this.ObjectId = null;
  }
}


}
