// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Gamium.Protocol.Types
{

public enum ExecuteRpcBy : short
{
  Method = 0,
  Field = 1,
  Property = 2,
};


}
