// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Gamium.Protocol.Types
{

public enum InputKeyPressType : short
{
  DOWN = 0,
  UP = 1,
};


}
