// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Gamium.Protocol.Types
{

public enum InputMousePressType : short
{
  DOWN = 0,
  UP = 1,
  MOVE = 2,
  SCROLL = 3,
};


}
