// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Gamium.Protocol.Types
{

public enum InputKeyBy : short
{
  UNITY_KEYCODE = 0,
  UNITY_KEYBOARD = 1,
};


}
