// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Gamium.Protocol.Types
{

public enum InputMouseButtonCode : short
{
  LEFT = 0,
  MIDDLE = 1,
  RIGHT = 2,
};


}
