// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Gamium.Protocol.Types
{

public enum ObjectLocatorBy : short
{
  Path = 0,
  Tag = 1,
};


}
