// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Gamium.Protocol.Types
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ObjectsHierarchy : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_10_26(); }
  public static ObjectsHierarchy GetRootAsObjectsHierarchy(ByteBuffer _bb) { return GetRootAsObjectsHierarchy(_bb, new ObjectsHierarchy()); }
  public static ObjectsHierarchy GetRootAsObjectsHierarchy(ByteBuffer _bb, ObjectsHierarchy obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ObjectsHierarchy __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
  public Gamium.Protocol.Types.ObjectHierarchyNode? Children(int j) { int o = __p.__offset(6); return o != 0 ? (Gamium.Protocol.Types.ObjectHierarchyNode?)(new Gamium.Protocol.Types.ObjectHierarchyNode()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ChildrenLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Gamium.Protocol.Types.ObjectsHierarchy> CreateObjectsHierarchy(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      VectorOffset childrenOffset = default(VectorOffset)) {
    builder.StartTable(2);
    ObjectsHierarchy.AddChildren(builder, childrenOffset);
    ObjectsHierarchy.AddName(builder, nameOffset);
    return ObjectsHierarchy.EndObjectsHierarchy(builder);
  }

  public static void StartObjectsHierarchy(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddChildren(FlatBufferBuilder builder, VectorOffset childrenOffset) { builder.AddOffset(1, childrenOffset.Value, 0); }
  public static VectorOffset CreateChildrenVector(FlatBufferBuilder builder, Offset<Gamium.Protocol.Types.ObjectHierarchyNode>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateChildrenVectorBlock(FlatBufferBuilder builder, Offset<Gamium.Protocol.Types.ObjectHierarchyNode>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateChildrenVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Gamium.Protocol.Types.ObjectHierarchyNode>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateChildrenVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Gamium.Protocol.Types.ObjectHierarchyNode>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartChildrenVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Gamium.Protocol.Types.ObjectsHierarchy> EndObjectsHierarchy(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // name
    return new Offset<Gamium.Protocol.Types.ObjectsHierarchy>(o);
  }
  public ObjectsHierarchyT UnPack() {
    var _o = new ObjectsHierarchyT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ObjectsHierarchyT _o) {
    _o.Name = this.Name;
    _o.Children = new List<Gamium.Protocol.Types.ObjectHierarchyNodeT>();
    for (var _j = 0; _j < this.ChildrenLength; ++_j) {_o.Children.Add(this.Children(_j).HasValue ? this.Children(_j).Value.UnPack() : null);}
  }
  public static Offset<Gamium.Protocol.Types.ObjectsHierarchy> Pack(FlatBufferBuilder builder, ObjectsHierarchyT _o) {
    if (_o == null) return default(Offset<Gamium.Protocol.Types.ObjectsHierarchy>);
    var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
    var _children = default(VectorOffset);
    if (_o.Children != null) {
      var __children = new Offset<Gamium.Protocol.Types.ObjectHierarchyNode>[_o.Children.Count];
      for (var _j = 0; _j < __children.Length; ++_j) { __children[_j] = Gamium.Protocol.Types.ObjectHierarchyNode.Pack(builder, _o.Children[_j]); }
      _children = CreateChildrenVector(builder, __children);
    }
    return CreateObjectsHierarchy(
      builder,
      _name,
      _children);
  }
}

public class ObjectsHierarchyT
{
  public string Name { get; set; }
  public List<Gamium.Protocol.Types.ObjectHierarchyNodeT> Children { get; set; }

  public ObjectsHierarchyT() {
    this.Name = null;
    this.Children = null;
  }
}


}
