name: 🐛 Bug Report
description: Please explain something that's not working in proper way.
body:
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the bug? Please provide specific steps if possible.
      placeholder: |-
        1. foo
        2. bar
        3. baz
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected result
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual result
      description: What actually happened? Please include any relevant error messages and/or screenshots.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: x.y.z (semver)
      description: What version are you using?
    validations:
      required: true
