name: 💡 Feature Request
title: '[Feature]: '
description: If you have a brilliant idea, don't hesitate to share it!
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What is the problem that we can solve?
      placeholder: |-
        I would like to brew coffee with water at different temperatures, but Gamium can only brew coffee with a fixed temperature of water.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Solution brainstorm
      description: What are the ways to solve the problem? You don't have to be specific. Please share your thoughts.
      placeholder: |-
        Add a temperature setting to Gamium.
    validations:
      required: true
