# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Packets

class ActionParam(object):
    NONE = 0
    Actions_SleepParam = 1
    Actions_InputKeyParam = 2
    Actions_InputMouseParam = 3
    Actions_InputSetTextParam = 4
    Actions_MovePlayerParam = 5
    Actions_AppQuitParam = 6

def ActionParamCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == ActionParam().Actions_SleepParam:
        import gamium.Protocol.Packets.Actions.SleepParam
        return gamium.Protocol.Packets.Actions.SleepParam.SleepParamT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == ActionParam().Actions_InputKeyParam:
        import gamium.Protocol.Packets.Actions.InputKeyParam
        return gamium.Protocol.Packets.Actions.InputKeyParam.InputKeyParamT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == ActionParam().Actions_InputMouseParam:
        import gamium.Protocol.Packets.Actions.InputMouseParam
        return gamium.Protocol.Packets.Actions.InputMouseParam.InputMouseParamT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == ActionParam().Actions_InputSetTextParam:
        import gamium.Protocol.Packets.Actions.InputSetTextParam
        return gamium.Protocol.Packets.Actions.InputSetTextParam.InputSetTextParamT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == ActionParam().Actions_MovePlayerParam:
        import gamium.Protocol.Packets.Actions.MovePlayerParam
        return gamium.Protocol.Packets.Actions.MovePlayerParam.MovePlayerParamT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == ActionParam().Actions_AppQuitParam:
        import gamium.Protocol.Packets.Actions.AppQuitParam
        return gamium.Protocol.Packets.Actions.AppQuitParam.AppQuitParamT.InitFromBuf(table.Bytes, table.Pos)
    return None
