# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Protocol

class Param(object):
    NONE = 0
    Packets_HelloParam = 1
    Packets_QueryScreenParam = 2
    Packets_FindObjectsParam = 3
    Packets_QueryObjectInteractableParam = 4
    Packets_ActionsParam = 5
    Packets_ExecuteRpcParam = 6
    Packets_InspectObjectOnScreenParam = 7
    Packets_InspectObjectWithIdParam = 8
    Packets_DumpObjectsHierarchyParam = 9
    Packets_ChangeConfigurationParam = 10
    Packets_QueryProfileParam = 11

def ParamCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == Param().Packets_HelloParam:
        import gamium.Protocol.Packets.HelloParam
        return gamium.Protocol.Packets.HelloParam.HelloParamT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Param().Packets_QueryScreenParam:
        import gamium.Protocol.Packets.QueryScreenParam
        return gamium.Protocol.Packets.QueryScreenParam.QueryScreenParamT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Param().Packets_FindObjectsParam:
        import gamium.Protocol.Packets.FindObjectsParam
        return gamium.Protocol.Packets.FindObjectsParam.FindObjectsParamT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Param().Packets_QueryObjectInteractableParam:
        import gamium.Protocol.Packets.QueryObjectInteractableParam
        return gamium.Protocol.Packets.QueryObjectInteractableParam.QueryObjectInteractableParamT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Param().Packets_ActionsParam:
        import gamium.Protocol.Packets.ActionsParam
        return gamium.Protocol.Packets.ActionsParam.ActionsParamT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Param().Packets_ExecuteRpcParam:
        import gamium.Protocol.Packets.ExecuteRpcParam
        return gamium.Protocol.Packets.ExecuteRpcParam.ExecuteRpcParamT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Param().Packets_InspectObjectOnScreenParam:
        import gamium.Protocol.Packets.InspectObjectOnScreenParam
        return gamium.Protocol.Packets.InspectObjectOnScreenParam.InspectObjectOnScreenParamT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Param().Packets_InspectObjectWithIdParam:
        import gamium.Protocol.Packets.InspectObjectWithIdParam
        return gamium.Protocol.Packets.InspectObjectWithIdParam.InspectObjectWithIdParamT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Param().Packets_DumpObjectsHierarchyParam:
        import gamium.Protocol.Packets.DumpObjectsHierarchyParam
        return gamium.Protocol.Packets.DumpObjectsHierarchyParam.DumpObjectsHierarchyParamT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Param().Packets_ChangeConfigurationParam:
        import gamium.Protocol.Packets.ChangeConfigurationParam
        return gamium.Protocol.Packets.ChangeConfigurationParam.ChangeConfigurationParamT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Param().Packets_QueryProfileParam:
        import gamium.Protocol.Packets.QueryProfileParam
        return gamium.Protocol.Packets.QueryProfileParam.QueryProfileParamT.InitFromBuf(table.Bytes, table.Pos)
    return None
