// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Gamium.Protocol.Packets.Actions
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct InputSetTextParam : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_10_26(); }
  public static InputSetTextParam GetRootAsInputSetTextParam(ByteBuffer _bb) { return GetRootAsInputSetTextParam(_bb, new InputSetTextParam()); }
  public static InputSetTextParam GetRootAsInputSetTextParam(ByteBuffer _bb, InputSetTextParam obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public InputSetTextParam __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string ObjectId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetObjectIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetObjectIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetObjectIdArray() { return __p.__vector_as_array<byte>(4); }
  public string Text { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTextBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetTextBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetTextArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<Gamium.Protocol.Packets.Actions.InputSetTextParam> CreateInputSetTextParam(FlatBufferBuilder builder,
      StringOffset object_idOffset = default(StringOffset),
      StringOffset textOffset = default(StringOffset)) {
    builder.StartTable(2);
    InputSetTextParam.AddText(builder, textOffset);
    InputSetTextParam.AddObjectId(builder, object_idOffset);
    return InputSetTextParam.EndInputSetTextParam(builder);
  }

  public static void StartInputSetTextParam(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddObjectId(FlatBufferBuilder builder, StringOffset objectIdOffset) { builder.AddOffset(0, objectIdOffset.Value, 0); }
  public static void AddText(FlatBufferBuilder builder, StringOffset textOffset) { builder.AddOffset(1, textOffset.Value, 0); }
  public static Offset<Gamium.Protocol.Packets.Actions.InputSetTextParam> EndInputSetTextParam(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Gamium.Protocol.Packets.Actions.InputSetTextParam>(o);
  }
  public InputSetTextParamT UnPack() {
    var _o = new InputSetTextParamT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(InputSetTextParamT _o) {
    _o.ObjectId = this.ObjectId;
    _o.Text = this.Text;
  }
  public static Offset<Gamium.Protocol.Packets.Actions.InputSetTextParam> Pack(FlatBufferBuilder builder, InputSetTextParamT _o) {
    if (_o == null) return default(Offset<Gamium.Protocol.Packets.Actions.InputSetTextParam>);
    var _object_id = _o.ObjectId == null ? default(StringOffset) : builder.CreateString(_o.ObjectId);
    var _text = _o.Text == null ? default(StringOffset) : builder.CreateString(_o.Text);
    return CreateInputSetTextParam(
      builder,
      _object_id,
      _text);
  }
}

public class InputSetTextParamT
{
  public string ObjectId { get; set; }
  public string Text { get; set; }

  public InputSetTextParamT() {
    this.ObjectId = null;
    this.Text = null;
  }
}


}
