// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Gamium.Protocol.Packets.Actions
{

public enum MovePlayerBy : short
{
  KeyPress = 0,
  Navigation = 1,
};


}
