// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Gamium.Protocol
{

public enum Param : byte
{
  NONE = 0,
  Packets_HelloParam = 1,
  Packets_QueryScreenParam = 2,
  Packets_FindObjectsParam = 3,
  Packets_QueryObjectInteractableParam = 4,
  Packets_ActionsParam = 5,
  Packets_ExecuteRpcParam = 6,
  Packets_InspectObjectOnScreenParam = 7,
  Packets_InspectObjectWithIdParam = 8,
  Packets_DumpObjectsHierarchyParam = 9,
  Packets_ChangeConfigurationParam = 10,
  Packets_QueryProfileParam = 11,
};

public class ParamUnion {
  public Param Type { get; set; }
  public object Value { get; set; }

  public ParamUnion() {
    this.Type = Param.NONE;
    this.Value = null;
  }

  public T As<T>() where T : class { return this.Value as T; }
  public Gamium.Protocol.Packets.HelloParamT AsPackets_HelloParam() { return this.As<Gamium.Protocol.Packets.HelloParamT>(); }
  public static ParamUnion FromPackets_HelloParam(Gamium.Protocol.Packets.HelloParamT _packets_helloparam) { return new ParamUnion{ Type = Param.Packets_HelloParam, Value = _packets_helloparam }; }
  public Gamium.Protocol.Packets.QueryScreenParamT AsPackets_QueryScreenParam() { return this.As<Gamium.Protocol.Packets.QueryScreenParamT>(); }
  public static ParamUnion FromPackets_QueryScreenParam(Gamium.Protocol.Packets.QueryScreenParamT _packets_queryscreenparam) { return new ParamUnion{ Type = Param.Packets_QueryScreenParam, Value = _packets_queryscreenparam }; }
  public Gamium.Protocol.Packets.FindObjectsParamT AsPackets_FindObjectsParam() { return this.As<Gamium.Protocol.Packets.FindObjectsParamT>(); }
  public static ParamUnion FromPackets_FindObjectsParam(Gamium.Protocol.Packets.FindObjectsParamT _packets_findobjectsparam) { return new ParamUnion{ Type = Param.Packets_FindObjectsParam, Value = _packets_findobjectsparam }; }
  public Gamium.Protocol.Packets.QueryObjectInteractableParamT AsPackets_QueryObjectInteractableParam() { return this.As<Gamium.Protocol.Packets.QueryObjectInteractableParamT>(); }
  public static ParamUnion FromPackets_QueryObjectInteractableParam(Gamium.Protocol.Packets.QueryObjectInteractableParamT _packets_queryobjectinteractableparam) { return new ParamUnion{ Type = Param.Packets_QueryObjectInteractableParam, Value = _packets_queryobjectinteractableparam }; }
  public Gamium.Protocol.Packets.ActionsParamT AsPackets_ActionsParam() { return this.As<Gamium.Protocol.Packets.ActionsParamT>(); }
  public static ParamUnion FromPackets_ActionsParam(Gamium.Protocol.Packets.ActionsParamT _packets_actionsparam) { return new ParamUnion{ Type = Param.Packets_ActionsParam, Value = _packets_actionsparam }; }
  public Gamium.Protocol.Packets.ExecuteRpcParamT AsPackets_ExecuteRpcParam() { return this.As<Gamium.Protocol.Packets.ExecuteRpcParamT>(); }
  public static ParamUnion FromPackets_ExecuteRpcParam(Gamium.Protocol.Packets.ExecuteRpcParamT _packets_executerpcparam) { return new ParamUnion{ Type = Param.Packets_ExecuteRpcParam, Value = _packets_executerpcparam }; }
  public Gamium.Protocol.Packets.InspectObjectOnScreenParamT AsPackets_InspectObjectOnScreenParam() { return this.As<Gamium.Protocol.Packets.InspectObjectOnScreenParamT>(); }
  public static ParamUnion FromPackets_InspectObjectOnScreenParam(Gamium.Protocol.Packets.InspectObjectOnScreenParamT _packets_inspectobjectonscreenparam) { return new ParamUnion{ Type = Param.Packets_InspectObjectOnScreenParam, Value = _packets_inspectobjectonscreenparam }; }
  public Gamium.Protocol.Packets.InspectObjectWithIdParamT AsPackets_InspectObjectWithIdParam() { return this.As<Gamium.Protocol.Packets.InspectObjectWithIdParamT>(); }
  public static ParamUnion FromPackets_InspectObjectWithIdParam(Gamium.Protocol.Packets.InspectObjectWithIdParamT _packets_inspectobjectwithidparam) { return new ParamUnion{ Type = Param.Packets_InspectObjectWithIdParam, Value = _packets_inspectobjectwithidparam }; }
  public Gamium.Protocol.Packets.DumpObjectsHierarchyParamT AsPackets_DumpObjectsHierarchyParam() { return this.As<Gamium.Protocol.Packets.DumpObjectsHierarchyParamT>(); }
  public static ParamUnion FromPackets_DumpObjectsHierarchyParam(Gamium.Protocol.Packets.DumpObjectsHierarchyParamT _packets_dumpobjectshierarchyparam) { return new ParamUnion{ Type = Param.Packets_DumpObjectsHierarchyParam, Value = _packets_dumpobjectshierarchyparam }; }
  public Gamium.Protocol.Packets.ChangeConfigurationParamT AsPackets_ChangeConfigurationParam() { return this.As<Gamium.Protocol.Packets.ChangeConfigurationParamT>(); }
  public static ParamUnion FromPackets_ChangeConfigurationParam(Gamium.Protocol.Packets.ChangeConfigurationParamT _packets_changeconfigurationparam) { return new ParamUnion{ Type = Param.Packets_ChangeConfigurationParam, Value = _packets_changeconfigurationparam }; }
  public Gamium.Protocol.Packets.QueryProfileParamT AsPackets_QueryProfileParam() { return this.As<Gamium.Protocol.Packets.QueryProfileParamT>(); }
  public static ParamUnion FromPackets_QueryProfileParam(Gamium.Protocol.Packets.QueryProfileParamT _packets_queryprofileparam) { return new ParamUnion{ Type = Param.Packets_QueryProfileParam, Value = _packets_queryprofileparam }; }

  public static int Pack(Google.FlatBuffers.FlatBufferBuilder builder, ParamUnion _o) {
    switch (_o.Type) {
      default: return 0;
      case Param.Packets_HelloParam: return Gamium.Protocol.Packets.HelloParam.Pack(builder, _o.AsPackets_HelloParam()).Value;
      case Param.Packets_QueryScreenParam: return Gamium.Protocol.Packets.QueryScreenParam.Pack(builder, _o.AsPackets_QueryScreenParam()).Value;
      case Param.Packets_FindObjectsParam: return Gamium.Protocol.Packets.FindObjectsParam.Pack(builder, _o.AsPackets_FindObjectsParam()).Value;
      case Param.Packets_QueryObjectInteractableParam: return Gamium.Protocol.Packets.QueryObjectInteractableParam.Pack(builder, _o.AsPackets_QueryObjectInteractableParam()).Value;
      case Param.Packets_ActionsParam: return Gamium.Protocol.Packets.ActionsParam.Pack(builder, _o.AsPackets_ActionsParam()).Value;
      case Param.Packets_ExecuteRpcParam: return Gamium.Protocol.Packets.ExecuteRpcParam.Pack(builder, _o.AsPackets_ExecuteRpcParam()).Value;
      case Param.Packets_InspectObjectOnScreenParam: return Gamium.Protocol.Packets.InspectObjectOnScreenParam.Pack(builder, _o.AsPackets_InspectObjectOnScreenParam()).Value;
      case Param.Packets_InspectObjectWithIdParam: return Gamium.Protocol.Packets.InspectObjectWithIdParam.Pack(builder, _o.AsPackets_InspectObjectWithIdParam()).Value;
      case Param.Packets_DumpObjectsHierarchyParam: return Gamium.Protocol.Packets.DumpObjectsHierarchyParam.Pack(builder, _o.AsPackets_DumpObjectsHierarchyParam()).Value;
      case Param.Packets_ChangeConfigurationParam: return Gamium.Protocol.Packets.ChangeConfigurationParam.Pack(builder, _o.AsPackets_ChangeConfigurationParam()).Value;
      case Param.Packets_QueryProfileParam: return Gamium.Protocol.Packets.QueryProfileParam.Pack(builder, _o.AsPackets_QueryProfileParam()).Value;
    }
  }
}


}
