name: ci-docs

on:
  push:
    paths:
      - docs/**
  pull_request:
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./docs

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build
        run: |
          yarn install && yarn build
        working-directory: ${{ env.working-directory }}
